[BigQuery] added user agent
GoogleCloudPlatform/jupyter-extensions pull request #340
Opened 2020-09-14 19:13 UTC by MRzNone

2020-09-14 19:42 UTC, cbwilkes requested changes

2020-09-14 19:42 UTC, cbwilkes commented on jupyterlab_bigquery/jupyterlab_bigquery/details_handler/service.py
> +                   user_agent='jupyterlab_bigquery/{}'.format(VERSION)))):
For all of these can you just set it to `'jupyterlab_gcpextension'`

2020-09-15 12:56 UTC, cbwilkes requested changes

2020-09-15 12:56 UTC, cbwilkes commented on jupyterlab_bigquery/jupyterlab_bigquery/pagedAPI_handler/pagedQuery_handler.py
> +          user_agent='jupyterlab_gcpextension/{}'.format(VERSION)))
Also take away the `{}'.format(VERSION)`. Just use `bigquery.Client(client_info=ClientInfo(user_agent='jupyterlab_gcpextension')`

2020-09-15 18:28 UTC, cbwilkes commented on jupyterlab_bigquery/jupyterlab_bigquery/details_handler/service.py
> +                   user_agent='jupyterlab_bigquery/{}'.format(VERSION)))):
Per our discussion set `user_agent` to `'jupyterlab_gcpextension/jupyterlab_bigquery-{}'.format(VERSION)`

2020-09-15 18:43 UTC, MRzNone commented
Discussed offline, will resolute to using `'jupyterlab_gcpextension/jupyterlab_bigquery-{}'.format(VERSION)`

2020-09-15 18:58 UTC, cbwilkes approved these changes

2020-09-15 19:01 UTC, cbwilkes commented
Submitting for now but in the future we should probably create the Client info in a central location

2020-09-15 19:01 UTC, merged